version: '3.8'

services:
  drake:
    build:
      context: .
      dockerfile: Dockerfile
    image: drake:my-project
    container_name: drake
    volumes:
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - .:/drake
      - /drake/.venv
    working_dir: /drake
    network_mode: host
    stdin_open: true
    tty: true
    command: bash
